# Generated by Django 6.0.3 on 2026-05-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_contactquery_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactquery',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
